### ISSUE TITLE
Rhino Inside: Revit. Build did not produce .addon file

### ISSUE THREAD

**Issue by shu-toz** [mcneel/rhino.inside#90]
Hi All,

When I followed the instructions to build the solution, it seems like there's no .addon file that was produced. 
Any ideas on what's missing? there's no error messages as the build was successful.

![Screenshot_1](https://user-images.githubusercontent.com/29880430/57337531-163d4980-716d-11e9-87d8-899336bc574a.png)

**Comment by kike-garbo** [comment]
Hi,

The project has two configurations:
1. **Debug** This configuration is mainly for development. Is configured to copy the .dll file and the .addon file at `%APPDATA%\Roaming\Autodesk\Revit\Addins\2019\` that is where Revit looks for installed addons and be able to debug it without any manual copying. 
2. **Release** This configuration is for generate the release version of the plugin. It does not copy anything in the %APPDATA%, instead is configured to just build the binaries to after that be able to generate the MSI file.

So if you compile in Debug Revit will load your addon next time you launch it, if instead of that you compile all the Release configurations and then build the Setup you will have an MSI installer to install the addon.

Does it help?

**Comment by shu-toz** [comment]
Hi,

I tried building this in the RELEASE configuration, but I did not get an MSI installer file...
However with DEBUG, I could get it functioning in the revit environment.

Thanks!

**Comment by kike-garbo** [comment]
To have an installer you need to build in Release 2017, Release 2018 and Release 2019 then open the other solution called `RhinoInside.Revit.Setup.sln` and build it in Release.

**Comment by kike-garbo** [comment]
[Here](https://ci.appveyor.com/project/mcneel/rhino-inside/branch/master/artifacts) you have an installer.
